version: '3.8'
services:

  db:
    container_name: postgres_container
    image: postgres:14.0
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - postgres
    restart: always


#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#
#    ports:
#      - "${PGADMIN_PORT:-5050}:80"
#    networks:
#      - postgres
#    restart: unless-stopped

  api_gateway:
    image: kong
    networks:
      - "kong-net"
    volumes:
      - ./kong/declarative:/kong/declarative
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml"
      - "KONG_DATABASE=off"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl"
  # kong_database:
  #   image: postgres:9.6
  #   environment:
  #     - POSTGRES_USER=kong
  #     - POSTGRES_DB=kong
  #     - POSTGRES_PASSWORD=kongpass
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - kong-net
  rest:
    image: quarkus/quarkus-kotlin-rest-api-jvm
    build:
      context: ./apps/quarkus-kotlin-rest-api
      dockerfile: ./src/main/docker/Dockerfile.jvm
    networks:
      - "kong-net"
    ports:
      - "8080"
      # - "8080:8080"
    # environment:
    #   JAVA_OPTS: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
    #   JAVA_APP_JAR: "/deployments/quarkus-kotlin-rest-api-1.0.0-SNAPSHOT.jar"
    volumes:
      - ./apps/quarkus-kotlin-rest-api/target/quarkus-app:/deployments

networks:
  kong-net:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: