apiVersion: v1
kind: Service
metadata:
    name: db
spec:
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
    name: db
subsets:
    - addresses:
        - ip: 192.168.49.1
      ports:
        - port: 5432
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     kompose.cmd: kompose convert
#     kompose.version: 1.26.0 (40646f47)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: db
#   name: db
# spec:
#   ports:
#     - name: "5432"
#       port: 5432
#       targetPort: 5432
#   selector:
#     io.kompose.service: db
# status:
#   loadBalancer: {}
