version: '3.8'
services:
  backend:
    container_name: gisa-backend
    image: andrealoisio/tcc-puc-backend:202204131925
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gisa
  
  frontend:
    container_name: gisa-frontend
    image: andrealoisio/tcc-puc-frontend:202204131952
    ports:
      - "3000:80"
  
  db:
    container_name: db
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gisa
