apiVersion: v1
kind: Service
metadata:
    name: kafka
spec:
    ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
---
apiVersion: v1
kind: Endpoints
metadata:
    name: kafka
subsets:
    - addresses:
        - ip: 192.168.49.1
      ports:
        - port: 9092